var GAME_LEVELS = [           
  ["                                                                                ",
   "                          oo                                                    ",
   "                                                                                ",
   "                  oo    xxxxx                                                   ",
   "                                                                                ",
   "                                                   oo                           ",
   "                xxxx                          oo                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "           oo                        o       xx                  x!!!x          ",
   "                                                                 xx!xx          ",
   "          xxxx                     xxxxx                          xvx           ",
   "                     LL                               oo                    xx  ",
   "  xx                                       oo                            o   x  ",
   "  x    xx                                                                o   x  ",
   "  x              mm       ||             xxxxx       xxxx     xxxx       o   x  ",
   "  x       o      mm                                                      o   x  ",
   "  x  @                                                           xxxx        x  ",
   "  xxxxxxxxxxxxxxxxxxxxx   xxxxx     xxxxx   xxxxx    xxxxxx    xxxxxxxxxxxxxxx  ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                 ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                  ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                   ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                    xxxx                                     x!x  ",
   "                                                                    x  x                                     x!x  ",
   "                         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxx                              o    x!x  ",
   "                         x!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                  o    x!x  ",
   "                         x !xxxxxxxxxxxxxxxxxxxxxxxx!!x                                              |  o    x!x  ",
   "                         x !x                     xx!x             o   o                                    xx!x  ",
   "           x x x x x x x x !x                      x!x                                        xxxxxxxxxxxxxxx!!x  ",
   "          !!!!!!!!!!!!!!!!! x                      xvx             xx  xx                    L   !!!!!!!!!!!!!!x  ",
   "          !x x x x x x x x x                                                xxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
   "          !                                                o     !!!!!!!!!               v                        ",
   "          !                                                    xxxx!!!!!xxxx                                      ",
   "          !                                    x                  xxxxxxx                  !!!!!                  ",
   "          !                                  xxx        o  xxx                             ! x x                  ",
   "          !                                    x                                           ! x                    ",
   "          !                                o   x                                 o         ! x                    ",
   "          !                                xxxxxx       xxxx                     o         ! x                    ",
   "          !                                    x                     x   x                 ! x                    ",
   " xxxxxxxxx!xxxx   |   xxxxxxxxxxx    xxx        x     x              x   x           o     ! x                    ",
   "          !                     x   x          x     x     xxxxxx    x   x      xxx  o     ! x                    ",
   "          !             xxxx    x  x          x    xx                x   x   x             ! x                    ",
   "     @    !                     x   x x x x x xx     x               x   x   x             ! x                    ",
   "    xxx   !                     x m  x                x              x    xxxxx      xxx   ! x                    ",
   "    x x   !                    xx  xx   ooo         x                x                     ! x                    ",
   "    x x!!!!!!x         x!!!!!!xx     xx        xx    x!!!!!!!!!!     x     =               ! x                    ",
   "    x x!!!!!!x         x!!!!!xx       xxx   xxxx     x!!!!!!!xx!     xxxxxxxxxxxxxxxx!!!!!!!xx                    ",
   "    x x!!!!!!x   ooo      x!!!x                      xx!!!!!!xx !                    xx!!!!!xx                    ",
   "    x x!!!!!!x                                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "      o                                xxxxxxxxxxxxxx!!!!!!xx   !                                                 ",
   "                       xxxxxxxxxx  xxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "xxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!  !!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x     o                      !!!  xxx                                ",
   "                                                                   o   !x!                                    ",
   "                                              x                    o    x                                     ",
   "                                      o     x                      o    x      xxx                            ",
   "                                                            x!         x       !!!                            ",
   "                                         x                  xxxxxxxxxxxx        x                             ",
   "                                     xx   xx          x      x                               xxx              ",
   "                                          xxxxxx      xxxxxxxx                              x!!!x             ",
   "                                          x     x                                            xvx              ",
   "                                  x        x    x                   o                                         ",
   "                                      o         xxx                                                           ",
   "                                                      x         o  xxxx                                       ",
   "                                      x               x            !!!!                                       ",
   "                                               = = = =x    o    x   xx      xxxxxx                            ",
   "                                        x x                                  !!!                              ",
   "                                          x                 x                |xv                              ",
   "                                          x           x              x                  o          |    |     ",
   "                            o  xxxxxxxxxxxxx          xxxxx!!!!!!!!!!x                                        ",
   "                               xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                               x           x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                           xxxx           xx                                o         xxxxx                   ",
   "  xxx                         x     x     x                                 o        x  x  x            xxx   ",
   "  x x      o  o          xxx  x    xxx    x                                         x   x   x         x x x   ",
   "  x        xxx                x  x     x   xxxxxxx            o           xxxxx         x   v          x   x  ",
   "  x       xxxxx        xxx    x           x                              x   x          x           xxxx   x  ",
   "  x       vxxxv               xx    o     x                              x x x        o x           x      x  ",
   "  x        xxx                      o     x       |xxxx|    |xxxx|     o xxxxx      x   x           x      x  ",
   "  x         x     xxx                                                    x           xxx       m    xxx       ",
   "  x            o xxxxx o      xx                                       xxxx                                x  ",
   "  x             ooxxxoo       x    xxx    x                              x                x  x  x x  x x  x   ",
   "  x               xxx        xxxxxxxxxxxxx  x    x    x    x    x    xxxxxx                               x   ",
   "  x      @         x         x           x  x    x!!!!x    x    x       x                                 x   ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                    !!!       ",
   "                                                                                      xxx           ! x       ",
   "                                                                                 o             o      x       ",
   "                                                                                        L      o    ! x       ",
   "        x x x          o                                                        xxx            o      x       ",
   "       x     x                                                                                      ! x       ",
   "      x       x      xxx                                                                              x       ",
   "                           o                                        xxxxx xxxxx xxxxx xxxxx xxxxx  ! xxx      ",
   "       x     x                                                         x o     o     o                        ",
   "       x= o  x            x                                       x xxx x xxx x xxx x xxx x xxx x    xx       ",
   "       x  o  x      o                                               x                         =     !         ",
   "          o         o                                        xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxx! xxx     ",
   "                                                         o                                          !         ",
   "               xxxxx    xxxxxxx                            xx                                       !         ",
   "               x   x    x     x                                                                               ",
   "           xxxxx   x    x     x             L                           o            x x   x        !         ",
   "                   x    x     x             L            xx                         x   x x  x      !         ",
   "                o  xxxxxx  o  xxxxxxxxx                                xxx         xxx        x     !         ",
   "  xxxxxx        o          o          x                            o            xxxxxxxxxxx                   ",
   "    x                                 x                                          x      x           !         ",
   "    x                                 xxxxxxx              xx     xx                                !         ",
   "    x     xxxxxxxxxxxxxxxxxxxxxxxxx         x                                                       L         ",
   "    x     x                         x       x        o                              ooo             o         ",
   "    x     x    0        0           x       xxxx                                     o              o         ",
   "  xxx   xxxxx   xxxxxxxxxxxxx    xx         x        x    ||                                        o         ",
   "  x         x   x           x               x                                  x          x         o         ",
   "  x         x   x           x   L  xx       x                                   x   x   x                     ",
   "  x  @      xxxxx           xxxxxxxxx     xxxxx                                                       !!!!!   ",
   "  xxxxxxx           o                         xxxxxxxxxxx    xxxx       xxx                   xxxxxxxx!!!!!   ",
   "        x=                  =                =x   x                     xxx    xxx                    !!!!!   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x  ooo oo!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                         x       x                  x       x       x   xxx    xx   x                         ",
   "                         x       x     ====          x     x x     x    x x    x x  x                         ",
   "                         x       x                    x   x   x   x     x x    x  x x                         ",
   "                          x     x      ====            x x     x x      x x    x   xx                         ",
   "                           x   x                        x       x       xxx    x    x                         ",
   "                            xxx                                                                               ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                @                       o                  o                  o                               ",
   "                                                                                                              ",
   "           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       ",
   "                                                                                                              ",
   "                                                                                                              "],
   ];
if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
