var GAME_LEVELS = [           
  ["                                                                                ",
   "                          oo                                                    ",
   "                                                                                ",
   "                  oo    xxxxx                                                   ",
   "                                                                                ",
   "                                                   oo                           ",
   "                xxxx                          oo                  xxx           ",
   "                                                   xx      xx    xx!xx          ",
   "           oo                        o       xx                  x!!!x          ",
   "                                                                 xx!xx          ",
   "          xxxx       LL              xxxxx                          xvx         ",
   "                     LL                               oo                    xx  ",
   "  xx                                       oo                                x  ",
   "  x    xx                                                                 o  x  ",
   "  x              mm       ||             xxxxx       xxxx     xxxx        o  x  ",
   "  x       o      mm                                                       o  x  ",
   "  x  @                                                           xxxx        x  ",
   "  xxxxxxxxxxxxxxxxxxxxx   xxxxx     xxxxx   xxxxx    xxxxxx    xxxxxxxxxxxxxxx  ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                 ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                  ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                   ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                    xxxx                                     x!x  ",
   "                                                                    x  x                                 o   x!x  ",
   "                         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxx                               o   x!x  ",
   "                         x!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                       x!x  ",
   "                         x !xxxxxxxxxxxxxxxxxxxxxxxx!!x                                              |       x!x  ",
   "                         x !x                     xx!x             o    o                                   xx!x  ",
   "           x x x x x x x x !x                      x!x                                   o    xxxxxxxxxxxxxxx!!x  ",
   "          !!!!!!!!!!!!!!!!! x                      xvx             xx  xx                        !!!!!!!!!!!!!!x  ",
   "          !x x x x x x x x x                                                xxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
   "          !                                                      !!!!!!!!!               v                        ",
   "          !                                                oo  xxxx!!!!!xxxx                                      ",
   "          !                                    x                  xxxxxxx                  !!!!!                  ",
   "          !                                  xxx           xxx                             ! x x                  ",
   "          !                                    x         o                                 ! x                    ",
   "          !                               o     x                                           ! x                   ",
   "          !                                xxxxxx       xxxx                               ! x                    ",
   "          !                                    x                     x   x                 ! x                    ",
   " xxxxxxxxx!xxxx   |   xxxxxxxxxxx    xxx        x     x              x    x                ! x                    ",
   "          !                     x   x        m x     x     xxxxxx    x   x      xxx  o     ! x                    ",
   "          !             xxxx    x  x          x    xx               x    x   x       o     ! x                    ",
   "     @    !                  =  x   x x x x x xx     x               x   x   x             ! x                    ",
   "    xxx   !                      x   x                x               x   xxxxx      xxx    ! x                   ",
   "    x x   !                     xx   xx   ooo         x               x                     ! x                   ",
   "    x x!!!!!!x        ox!!!!!!xx     xx        xx    x!!!!!!!!!!     x     =               ! x                    ",
   "    x x!!!!!!x  ooo    x!!!!!xx       xxx   xxxx     x!!!!!!!xx!     xxxxxxxxxxxxxxxx!!!!!!!xx                    ",
   "    x x!!!!!!x            x!!!x                      xx!!!!!!xx !                    xx!!!!!xx                    ",
   "    x x!!!!!!x                                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "      o                      oo        xxxxxxxxxxxxxx!!!!!!xx   !                                                 ",
   "                       xxxxxxxxxx  xxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "xxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!  !!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                      ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x  o                      o  !!!  xxx                                ",
   "                                                                   o  !x!                                     ",
   "                                              x          o         o   x                                      ",
   "                                            x            o             x       xxx            o               ",
   "                                     o                   o  x!         x       !!!            o               ",
   "                                         x                  xxxxxxxxxxxx        x                             ",
   "                                     xx   xx          x      x                               xxx              ",
   "                                  o       xxxxxx      xxxxxxxx                              x!!!x             ",
   "                                          x     x                    o                       xvx              ",
   "                                  x        x    x                    o                                        ",
   "                                      o         xxx                                                           ",
   "                                                      x            xxxx      ooo                              ",
   "                                      x               x            !!!!                                       ",
   "                                               = = = =x     o   x   xx      xxxxxx                            ",
   "                               o        x x                                  !!!                              ",
   "                               o          x                 x                |xv                              ",
   "                                          x           x              x                  o          |    |     ",
   "                               xxxxxxxxxxxxx          xxxxx!!!!!!!!!!x                  o                     ",
   "                         o     xxx x x xxx x          x!!!!!!!!!!!!!!x                  o                     ",
   "                         o  =  x           x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                           xxxx           xx                                          xxxxx                   ",
   "  xxx      o o                x     x     x                                          x  x  x            xxx   ",
   "  x x                    xxx  x    xxx    x                    o                    x   x   x         x x x   ",
   "  x        xxx      o          x  x     x   xxxxxxx            o           xxxxx         x   v         x   x  ",
   "  x       xxxxx     o   xxx  L x        L  x         oo        o    =     x   x          x          xxxx   x  ",
   "  x       vxxxv              L xx          x                              x x x          x           x     x  ",
   "  x        xxx                     ooo    x       |xxxx|    |xxxx|       xxxxx      x   x           x      x  ",
   "  x         x      xxx                                                   x           xxx     ooo    xxx       ",
   "  x             o xxxxx o     xx                o                      xxxx                                x  ",
   "  x              ooxxxoo      x    xxx    x     o                        x                 x  x  x x  x x  x  ",
   "  x                xxx        xxxxxxxxxxxxx  x  o x    x    x    x    xxxxxx                               x  ",
   "  x      @          x         x           x  x    x!!!!x    x    x       x                                 x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                    !!!       ",
   "                                                                                      xxx           ! x       ",
   "                                                                                                      x       ",
   "                                                                                                    ! x       ",
   "        x x x                o                                                  xxx                   x       ",
   "       x     x                                                                               o o    ! x       ",
   "      x       x      xxx                                                  m                           x       ",
   "                                                                    xxxxx xxxxx xxxxx xxxxx xxxxx  ! xxx      ",
   "       x     x                                                         x o     o     o            o           ",
   "       x= o  x            x                                       x xxx x xxx x xxx x xxx x xxx x    xx       ",
   "       x     x                                                      x                         =     !         ",
   "          o               o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxx! xxx     ",
   "                                                                                                    !         ",
   "          o    xxxxx    xxxxxxx                            xx                                       !         ",
   "               x   x    x     x                                                          o                    ",
   "           xxxxx o x    x     x                                                      x x   x        !         ",
   "                   x    x     x                          xx                         x   x x  x      !         ",
   "                   xxxxxx     xxxxxxxxx                    o           xxx         xxx        x     !         ",
   "  xxxxxx                              x                                         xxxxxxxxxxx                   ",
   "    x                     o           x m                                        x      x           !         ",
   "    x          m                      xxxxxxx              xx     xx                                !         ",
   "    x     xxxxxxxxxxxxxxxxxxxxxxxxx         x        o                                              L         ",
   "    x     x                         x       x                                      ooo              o         ",
   "    x     x     o    o    o         x       xxxx                                    o               o         ",
   "  xxx   xxxxx   xxxxxxxxxxxxx    xx         x        x    ||                                        o         ",
   "  x         x   x           x               x                                  x          x         o         ",
   "  x         x   x           x   L  xx       x                                   x   x   x           o         ",
   "  x  @      xxxxx   o       xxxxxxxxx     xxxxx                                                       !!!!!   ",
   "  xxxxxxx                                     xxxxxxxxxxx    xxxx       xxx                   xxxxxxxx!!!!!   ",
   "        x=                  =                =x   x                     xxx    xxx                    !!!!!   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x  ooo oo!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
